<?php
/**
 * SearchRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\NoodleSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Noodle Setup API
 *
 * API that allows configure programs for Noodle
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Softonic\NoodleSetupApiSdk;

/**
 * SearchRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description SearchRequest
/**
 * @package     Softonic\NoodleSetupApiSdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchRequest"
     */
    public function testSearchRequest()
    {
    }

    /**
     * Test attribute "id_program"
     */
    public function testPropertyIdProgram()
    {
    }

    /**
     * Test attribute "id_platform"
     */
    public function testPropertyIdPlatform()
    {
    }

    /**
     * Test attribute "id_locale"
     */
    public function testPropertyIdLocale()
    {
    }
}
