<?php
/**
 * ProgramLocaleConfigurationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\NoodleSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Noodle Setup API
 *
 * API that allows configure programs for Noodle
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\NoodleSetupApiSdk;

use \Softonic\NoodleSetupApiSdk\Configuration;
use \Softonic\NoodleSetupApiSdk\ApiException;
use \Softonic\NoodleSetupApiSdk\ObjectSerializer;

/**
 * ProgramLocaleConfigurationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\NoodleSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramLocaleConfigurationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for programsIdProgramLocalesGet
     *
     * Finds configurations for program in all Softonic locales.
     *
     */
    public function testProgramsIdProgramLocalesGet()
    {
    }

    /**
     * Test case for programsIdProgramLocalesIdLocaleDelete
     *
     * Deletes a program configuration for a specific locale.
     *
     */
    public function testProgramsIdProgramLocalesIdLocaleDelete()
    {
    }

    /**
     * Test case for programsIdProgramLocalesIdLocaleGet
     *
     * Finds configurations for program and Softonic locale.
     *
     */
    public function testProgramsIdProgramLocalesIdLocaleGet()
    {
    }

    /**
     * Test case for programsIdProgramLocalesIdLocalePatch
     *
     * Updates a program configuration for a specific locale.
     *
     */
    public function testProgramsIdProgramLocalesIdLocalePatch()
    {
    }

    /**
     * Test case for programsIdProgramLocalesIdLocalePut
     *
     * Replaces a program configuration for a specific locale.
     *
     */
    public function testProgramsIdProgramLocalesIdLocalePut()
    {
    }

    /**
     * Test case for programsIdProgramLocalesPost
     *
     * Creates a program configuration for a specific locale.
     *
     */
    public function testProgramsIdProgramLocalesPost()
    {
    }
}
