<?php
/**
 * ProgramsPlatformsLocalesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Softonic\NoodleSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Noodle Setup API
 *
 * API that allows configure programs for Noodle
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@softonic.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Softonic\NoodleSetupApiSdk;

use \Softonic\NoodleSetupApiSdk\Configuration;
use \Softonic\NoodleSetupApiSdk\ApiException;
use \Softonic\NoodleSetupApiSdk\ObjectSerializer;

/**
 * ProgramsPlatformsLocalesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Softonic\NoodleSetupApiSdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsPlatformsLocalesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createProgramPlatformLocale
     *
     * Creates a program configuration for a specific platform and locale.
     *
     */
    public function testCreateProgramPlatformLocale()
    {
    }

    /**
     * Test case for deleteProgramPlatformLocale
     *
     * Deletes a program configuration for a specific platform and locale.
     *
     */
    public function testDeleteProgramPlatformLocale()
    {
    }

    /**
     * Test case for findProgramPlatformLocale
     *
     * Finds a program configuration for a specific platform for all locales.
     *
     */
    public function testFindProgramPlatformLocale()
    {
    }

    /**
     * Test case for readProgramPlatformLocale
     *
     * Reads a program configuration for a specific platform and locale.
     *
     */
    public function testReadProgramPlatformLocale()
    {
    }

    /**
     * Test case for replaceProgramPlatformLocale
     *
     * Replaces a program configuration for a specific platform and locale.
     *
     */
    public function testReplaceProgramPlatformLocale()
    {
    }

    /**
     * Test case for updateProgramPlatformLocale
     *
     * Updates a program configuration for a specific platform and locale.
     *
     */
    public function testUpdateProgramPlatformLocale()
    {
    }
}
